
import html2pdf from 'html2pdf.js';
import { MealPlan } from '@/types/meal';

const formatDate = (dateStr: string): string => {
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-US', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
};

export const exportMealPlanToPdf = (mealPlan: MealPlan, nutritionSummary: { calories: number, protein: number }) => {
  // Create a temporary div element to hold the content
  const element = document.createElement('div');
  element.style.width = '210mm'; // A4 width
  element.style.padding = '15mm';
  element.style.backgroundColor = 'white';
  element.style.color = 'black';
  
  // Add header
  const header = document.createElement('div');
  header.style.textAlign = 'center';
  header.style.marginBottom = '15px';
  header.innerHTML = `
    <h1 style="color: #22c55e; font-size: 24px; margin-bottom: 5px;">Veggie Gain-o-Meter</h1>
    <h2 style="font-size: 18px; margin-top: 0;">Meal Plan for ${formatDate(mealPlan.date)}</h2>
  `;
  element.appendChild(header);
  
  // Add nutrition summary
  const summary = document.createElement('div');
  summary.style.marginBottom = '20px';
  summary.style.padding = '10px';
  summary.style.backgroundColor = '#f0fdf4';
  summary.style.borderRadius = '8px';
  summary.style.border = '1px solid #86efac';
  summary.innerHTML = `
    <h3 style="margin-top: 0; color: #15803d;">Nutrition Summary</h3>
    <p><strong>Total Calories:</strong> ${nutritionSummary.calories} kcal</p>
    <p><strong>Total Protein:</strong> ${nutritionSummary.protein}g</p>
  `;
  element.appendChild(summary);
  
  // Add meal plan content
  const mealTimeLabels: Record<string, string> = {
    morning: 'Morning (7:00 AM)',
    breakfast: 'Breakfast (8:00 AM)',
    midMorning: 'Mid-Morning Snack (11:00 AM)',
    lunch: 'Lunch (1:00 PM)',
    evening: 'Evening Snack (4:00 PM)',
    dinner: 'Dinner (8:00 PM)',
    beforeBed: 'Before Bed (10:00 PM)'
  };
  
  const mealsContent = document.createElement('div');
  
  Object.entries(mealPlan.meals).forEach(([mealTime, meals]) => {
    if (meals.length === 0) return;
    
    const mealSection = document.createElement('div');
    mealSection.style.marginBottom = '15px';
    
    const mealTitle = document.createElement('h3');
    mealTitle.style.backgroundColor = '#dcfce7';
    mealTitle.style.padding = '8px';
    mealTitle.style.borderRadius = '4px';
    mealTitle.style.marginBottom = '10px';
    mealTitle.style.color = '#166534';
    mealTitle.textContent = mealTimeLabels[mealTime] || mealTime;
    
    mealSection.appendChild(mealTitle);
    
    const mealItems = document.createElement('div');
    mealItems.style.paddingLeft = '15px';
    
    meals.forEach(meal => {
      const item = document.createElement('div');
      item.style.marginBottom = '10px';
      item.style.padding = '8px';
      item.style.backgroundColor = '#f9fafb';
      item.style.borderRadius = '4px';
      item.style.borderLeft = '3px solid #22c55e';
      
      item.innerHTML = `
        <h4 style="margin: 0 0 5px 0;">${meal.name}</h4>
        <p style="margin: 0; color: #4b5563; font-size: 14px;">${meal.description}</p>
        <p style="margin: 5px 0 0 0; font-size: 14px;">
          <span style="color: #f97316;">${meal.calories} calories</span> | 
          <span style="color: #8b5cf6;">${meal.protein}g protein</span>
        </p>
      `;
      
      mealItems.appendChild(item);
    });
    
    mealSection.appendChild(mealItems);
    mealsContent.appendChild(mealSection);
  });
  
  element.appendChild(mealsContent);
  
  // Add footer
  const footer = document.createElement('div');
  footer.style.marginTop = '20px';
  footer.style.textAlign = 'center';
  footer.style.borderTop = '1px solid #d1d5db';
  footer.style.paddingTop = '10px';
  footer.style.color = '#6b7280';
  footer.style.fontSize = '12px';
  footer.innerHTML = `
    <p>Generated by Veggie Gain-o-Meter on ${new Date().toLocaleDateString()}</p>
    <p>Your high-calorie vegetarian meal planner for healthy weight gain</p>
  `;
  element.appendChild(footer);
  
  // Create PDF using html2pdf
  const opt = {
    margin: 10,
    filename: `Meal_Plan_${mealPlan.date}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };
  
  html2pdf().set(opt).from(element).save();
};
